name: CI Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  build-and-test:

    uses: ./.github/workflows/reusable-build.yml
