name: Reusable Build Workflow

on:
  workflow_call:

jobs:

  reusable-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Build Message
        run: echo "Reusable workflow executed successfully"
